# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/Dockerfile

FROM jupyterhub/k8s-hub:v0.5.0

COPY k8s-hub/templates /usr/local/share/jupyter/hub/templates

# Include base_url in cull script - this is in the git version but this image doesnt include it :/
USER root
RUN sed -i "s#'--url=http://127.0.0.1:8081/hub/api'#'--url=http://127.0.0.1:8081/h/hub/api'#" /srv/jupyterhub_config.py
USER jovyan
